### ISSUE TITLE
Add NLopt

### ISSUE THREAD

**Issue by ChrisRackauckas** [jonathanBieler/BlackBoxOptimizationBenchmarking.jl#2]
NLopt is probably the best choice in Julia right now. Would be good to see it in the list.

**Comment by jonathanBieler** [comment]
Which algorithm do you think would perform well ? I've tried a couple of them by I didn't manage to get decent results. Note that it need to be global (otherwise it will perform like the simplex) and derivative free.

**Comment by ChrisRackauckas** [comment]
You tried all of https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#global-optimization ?

Could you show it not performing well then? I'm sure @stevengj might be able to help find out what the issue is. `NLOPT_GN_DIRECT_L` is a pretty good algorithm when you don't have constraints, `NLOPT_GN_ISRES` is slow but always seems to work and can handle equality constraints. It's at least worth showing if it they fail. I found those massively better than BlackBoxOptim, so I'd be surprised if they didn't at least perform as well as BBO.

**Comment by ChrisRackauckas** [comment]
It's probably also worth showing IPOPT. Even though it's technically local, it can do better then one would think in many cases.

**Comment by jonathanBieler** [comment]
I'm getting a segfault with `GN_DIRECT_L` (and some others), I don't know if I do something wrong:

```julia
using BlackBoxOptimizationBenchmarking
const BBOB = BlackBoxOptimizationBenchmarking

using NLopt

D, run_length = 3, 5000
f = BBOB.F1

pinit(D) = 10*rand(D)-5

opt = Opt(:GN_DIRECT_L, D)
min_objective!(opt, (p,g) -> f(p) )

maxeval!(opt,run_length)
xtol_abs!(opt,1e-16)
xtol_rel!(opt,1e-16)
ftol_abs!(opt,1e-16)
ftol_rel!(opt,1e-16)
lower_bounds!(opt, -5*ones(D))
upper_bounds!(opt, +5*ones(D))

minf,minx,ret = NLopt.optimize(opt, pinit(D))
```

NLOPT_GN_ISRES doesn't manage to solve the Sphere function (probably because of the convergence issue mentioned in the doc).

**Comment by ChrisRackauckas** [comment]
NLopt's global optimizers are made to get into the vicinity of the global optimum and then be completed by a local optimizer. IMO trying to use them with `1e-16` tolerance is just using them wrong. Would you except a two-stage approach?

**Comment by jonathanBieler** [comment]
I think the lack of final convergence indicates that the algorithms are quite sensitive to rescaling of the axis of the function, which is not very good. But I did a chaining type where I do 10% of iterations with the simplex at the end, which helps to reach the minimum. The ones that don't segfault doesn't seem to beat CMA-ES but I'll add them to the benchmark.

**Comment by ChrisRackauckas** [comment]
Cool, thanks. It's interesting to see where they fall in comparison. Hopefully @stevengj can help you sort out why that's segfaulting since I'm not seeing why it would.

**Comment by ChrisRackauckas** [comment]
Thanks for adding it. So Optim and NLopt are fast but with a much lower success rate? That's good to know!
