### ISSUE TITLE
function instances

### ISSUE THREAD

**Issue by jotwin** [jonathanBieler/BlackBoxOptimizationBenchmarking.jl#6]
My understanding of the BBOB framework is that that the randomized components (such as rotations) are different in each function instance. 

Here it appears that the random parts are fixed once `using Black...` is called.

Is there a way to make different function instances?

**Comment by jonathanBieler** [comment]
Hi, I agree it would be nice to able to generate new rotations when needed.

Currently I'm using `Memoize.jl` to generate the [rotation matrices](https://github.com/jonathanBieler/BlackBoxOptimizationBenchmarking.jl/blob/master/src/BlackBoxOptimizationBenchmarking.jl#L62) only once.

I think just redefining these function into the module (using `@eval BlackBoxOptimizationBenchmarking begin ... end`) would work but I'm not totally sure, I can test tomorrow.

**Comment by jonathanBieler** [comment]
Indeed you can do :

```julia
@eval BlackBoxOptimizationBenchmarking begin
    @memoize function Q(D)
        r = randn(D); r = r/norm(r)
        Q = [r nullspace(Matrix(r'))]
    end
    @memoize function R(D)
        r = randn(D); r = r/norm(r)
        R = [r nullspace(Matrix(r'))]
    end
end
```

To get new rotations. 

Do you want a function for this, or that's enough ?

**Comment by jotwin** [comment]
This works for me, thanks!

**Comment by jonathanBieler** [comment]
Alright, I'll just add this in the README then.
